
server:
  port: 9191

spring:
  application:
    name: Backend
  datasource:
    username: root
    password: 12345
    url: jdbc:mysql://localhost:3306/hotel_db
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
  servlet:
    multipart:
    max-file-size: 1024MB
    max-request-size: 1024MB

springdoc:
  api-docs:
    path=/api-docs: